### PR TITLE
Specify in card names that COVID and COVID vaccination rates are cumulative

### PR DESCRIPTION
**Pull request by joshzarrabi**
## Preview Link

<a href="https://deploy-preview-1754--health-equity-tracker.netlify.app/exploredata?onboard=false" target="_blank">
  <br />
Click to demo updates </a> 

## Description

Rename COVID and COVID Vaccination cards to specify that the metrics are cumulative for the pandemic, as opposed to our other metrics which show the most recent time period we have data for. For example Poverty shows the 2019 ACS numbers, 

## Motivation and Context

We believe it is important to differentiate between this and our other metrics which are only for the latest year. 
Also, this will help differentiate between the cumulative and time based metrics are planning on adding in #1703 

## Screenshots (if appropriate):
Screen Shot 2022-08-16 at 12 55 52 PM

Screen Shot 2022-08-16 at 12 56 01 PM
Screen Shot 2022-08-16 at 12 56 07 PM
Screen Shot 2022-08-16 at 12 56 14 PM
Screen Shot 2022-08-16 at 12 56 22 PM

## Types of changes

- New feature (non-breaking change which adds functionality or content)

### CODE REVIEW

**Review by benhammondmusic — COMMENTED** [review]
I don't know if cumulative is the best word here. I think it makes me associate too much with a case count. I wonder if "all time" or similar is more clear?

**Comment by joshzarrabi** [comment]
@benhammondmusic I'm not a huge fan of "All Time", sounds too colloquial. I'm surprised you only associate cumulative with case counts, I think its the right word here.

**Comment by benhammondmusic** [comment]
> @benhammondmusic I'm not a huge fan of "All Time", sounds too colloquial. I'm surprised you only associate cumulative with case counts, I think its the right word here.

I guess it's fine because we are explicitly describing the RATE as `COUNT / POPULATION`, so it works to write out `"CUMULATIVE" COUNT / POPULATION`. But I don't think we can call it a "cumulative rate" (not that you have), because the rates don't accumulate, only the counts do. The only title change you made here that I'm not sure fits this is the Age-Adjusted ratio, because again we aren't accumulating ratios, we are accumulating counts and then calculating the ratios. 

I kind of feel like we need to be specifying the time range of the cumulative counts or something, to make it clear that it's 3 years worth of case counts (and growing) divided by a population.

**Comment by joshzarrabi** [comment]
Closing this in favor of #1718 Where the work will be done.

**Pull request closed without merging**
