### PR TITLE
Replaces Share Button with Social Share Icons

### PR DESCRIPTION
**Pull request by benhammondmusic**
- linkedin
- facebook
- twitter
- email

### CODE REVIEW

**Comment by benhammondmusic** [comment]
Got a meta image to show up by hardcoding it into the `public/index.html` file. This means it won't be dynamic based on the page. It appears we'll need to incorporate server side rendering to generate this image share dynamically but more research is needed on that

email
fb
linkedin 1
linkedin 2
twitter

**Comment by benhammondmusic** [comment]
Npr and cdc sites simply have the share icons at the bottom of the article; unlabeled image

image

**Comment by benhammondmusic** [comment]
- https://cards-dev.twitter.com/validator
- https://www.linkedin.com/post-inspector/
- https://developers.facebook.com/tools/debug/

**Comment by benhammondmusic** [comment]
Decided to remove the share button / modal and simply place the icons directly on the tracker. 

graphic is still set directly on the static `/public/index.html`; there is some possible trickery we could do to have multiple images (say for different variables etc) but to really generate a share image of a dynamic tracker visualization, we would need to implement some sort of server side rendering.

Screen Shot 2021-11-18 at 7 46 29 PM
Screen Shot 2021-11-18 at 7 46 44 PM
Screen Shot 2021-11-18 at 7 47 13 PM

**Comment by benhammondmusic** [comment]
request to include the `Share:` label per Mahia and @jgonzalezmsm

**Comment by benhammondmusic** [comment]
SHARE SCRNSHOT

**Review by joshzarrabi — APPROVED** [review]
Looks great, thanks for this.

**Pull request merged**
