### PR TITLE
Adds video demo to landing page and updates how to images and text

### LINKED ISSUE #1763: Need "How to Use" Section on Frontpage
## Is your feature request related to a problem? Please describe.

- An on-demand video demo is a helpful tool to familiarize users to the platform and to assist in outreach.
- We need a space on the Tracker to highlight the demo.

## Describe the solution you'd like

- Add a 4th content box under the "How to use the Data Tracker" with other various tweaks/enhancements. Write-Up [here](https://docs.google.com/document/d/1FX9EOFV6EgAx74Nq4wydb6_cr4dAaLOkNpsvqT9I_DU/edit?usp=sharing)

## Describe alternatives you've considered

- Feature Video Demo as blog post so it would display as a featured item
- Add to Resources page as a link/embedded

## Additional context
see [write up](https://docs.google.com/document/d/1FX9EOFV6EgAx74Nq4wydb6_cr4dAaLOkNpsvqT9I_DU/edit?usp=sharing)

### PR DESCRIPTION
**Pull request by joshzarrabi**
## Preview Link

<a href="https://deploy-preview-1772--health-equity-tracker.netlify.app/" target="_blank">
  <br />
Click to demo updates </a> 

## Description

* Updates the images and text in the "How to use" section of the landing page 
* Adds the video demo to the landing page

## Motivation and Context

Closes #1763

## How has this been tested?

Tested manually

## Screenshots (if appropriate):
Screen Shot 2022-09-01 at 1 20 06 PM

Screen Shot 2022-09-01 at 1 20 20 PM

## Types of changes

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Review by jgonzalezmsm — CHANGES_REQUESTED** [review]
looks great! we may need to update alt text for all screenshots? for example the incarceration screenshot still shows "Map Example Screenshot, Data Tracker map of Covid-19 rates of all racial groups" please confirm i'm looking at that correctly.

i can provide language for alt text

**Comment by joshzarrabi** [comment]
> looks great! we may need to update alt text for all screenshots? for example the incarceration screenshot still shows "Map Example Screenshot, Data Tracker map of Covid-19 rates of all racial groups" please confirm i'm looking at that correctly.
> 
> i can provide language for alt text

@jgonzalezmsm Good catch, sure, ill put it in when you have it

**Comment by jgonzalezmsm** [comment]
alt text for screenshots:

### Search by completing the sentence

alt text: no change

**Use filters to go deeper**

change from: "Search Example Screenshot: Compare Rates of option Covid-19 between two locations" -->  to "**Example Screenshot: Select demographic variables by interacting with the dropdown menu and other filters.**"

### Explore maps and graphs

change from: "Map Example Screenshot, Data Tracker map of Covid-19 rates of all racial groups" --> to "**Example Screenshot:  Map of individuals in prison per 100k in the state of Georgia.**"


we could possibly do more accessibility updates around this in a future release ..further reading: https://moz.com/blog/seo-accessibility-images-video

**Comment by joshzarrabi** [comment]
@jgonzalezmsm Thanks, updated the alt text

**Review by eriwarr — APPROVED** [review]
Great job!!!

**Review by jgonzalezmsm — APPROVED** [review]

**Pull request merged**
