### PR TITLE
Show races for which we don't have data in the table card for Covid

### PR DESCRIPTION
**Pull request by vanshkumar**

### CODE REVIEW

**Comment by vanshkumar** [comment]
Still need to add tests, but it works.. comparison of deploy-preview vs current dev site for NM:

Screen Shot 2021-05-16 at 1 21 54 PM
Screen Shot 2021-05-16 at 1 18 03 PM

**Review by joshzarrabi — APPROVED** [review]
Approving but tests would be great!

**Comment by vanshkumar** [comment]
> Approving but tests would be great!

Added tests

**Comment by vanshkumar** [comment]
Btw, one consequence of this change is that "Other" shows up with "no data" for all states now.. IMO this is fine but just wanted to call it out

**Comment by vanshkumar** [comment]
Upon further review, I think this slows the calculations for Covid down too much to be worth it.. going to just move the underlying issue to the backlog and we can fix it properly (i.e. add in the missing rows on the BE) later

**Pull request closed without merging**
