### PR TITLE
Fixes NaN% in suppressed states

### LINKED ISSUE #1267: NaN% in legend for suppressed states (some?)
Searching for covid deaths by age in some locations including 
- Delaware
- W Virginia
- S Dakota
- Nebraska
- Wyoming

(and likely others) https://healthequitytracker.org/exploredata?mls=1.covid-3.10&dt1=deaths&demo=age results in displaying an empty unknowns map with `NaN%` in the legend

This map shouldn't even display, right? It should be an alert box instead? 
nan legend

### PR DESCRIPTION
**Pull request by benhammondmusic**
fixes #1267 by only counting `Unknown` values that actually contain data

### CODE REVIEW

**Comment by benhammondmusic** [comment]
Screen Shot 2021-12-20 at 11 32 27 PM

**Comment by benhammondmusic** [comment]
What's the proper alert message here? Right now it's showing the info `No unknown values for Race And Ethnicity reported in this dataset.` but should it really be the orange alert `We do not currently have COVID-19 Deaths Per 100k People broken down by Race And Ethnicity at the county level. Learn more about how this lack of data impacts health equity.` @joshzarrabi  ?

**Comment by joshzarrabi** [comment]
@benhammondmusic Yeah it should be the yellow warning. Its not that there are zero unknowns but rather that we have no data.

**Comment by benhammondmusic** [comment]
moved to #1370

**Pull request closed without merging**
