### PR TITLE
Combines "About Us" subpages

### LINKED ISSUE #2831: Once methodology launched, condense "About Us" page
Currently, the top level link is to "About Us" and the three tabs are "The Project", "Our Team", and "Contact Us"

After the new methodology hub is live, it will include much of the info the "The Project" tab so that can be deleted

Additionally, we could combine Contact Us and Our Team into a single tab, with the contact info up top and then the team info and pics below.

### PR DESCRIPTION
**Pull request by benhammondmusic**
# Description and Motivation

- closes #2831 
- updates @kccrtv 's title
- adds @alinix1 and @JDemlow 
- removes "filler" that we've discussed removing since launch
- swaps email signup for new abstracted social links component
- aligns margins
- loads more fancy taviraj font weights allowing more styling options
- align formatting of grantors with partners

## Has this been tested? How?

tests passing

## Screenshots (if appropriate)

Screenshot 2024-02-06 at 2 07 10 PM
Screenshot 2024-02-06 at 2 07 02 PM
Screenshot 2024-02-06 at 2 06 40 PM
Screenshot 2024-02-06 at 2 06 34 PM
Screenshot 2024-02-06 at 10 10 56 AM
Screenshot 2024-02-06 at 2 14 14 PM

## Types of changes

(leave all that apply)

- New content or feature
- Refactor / chore

### CODE REVIEW

**Comment by eriwarr** [comment]
The wording in the subsections are hard for me to read. 

Screenshot 2024-02-06 at 1 31 17 PM

**Comment by eriwarr** [comment]
Can we apply the same styling to both sections? As we add more grantors, I think it may look better if they're formatted the same.

Screenshot 2024-02-06 at 1 33 12 PM

**Comment by benhammondmusic** [comment]
> The wording in the subsections are hard for me to read.
> 
> Screenshot 2024-02-06 at 1 31 17 PM

interesting; i dont have the 100 weight for that font on my computer so it's rendering at 300.... doesn't look like your screenshot at all!

**Review by eriwarr — APPROVED** [review]
Looks great!

**Pull request merged**
