### PR TITLE
Suppress blank maps

### PR DESCRIPTION
**Pull request by benhammondmusic**
if there is no data, don't generate the map (rather than displaying an entirely gray map). Better user experience as maps displaying the next geo level down of data, so there may be no data on the map but there really is data in the charts... having a blank map up top may keep the user from scrolling down to see the data filled charts

### CODE REVIEW

**Review by joshzarrabi — APPROVED** [review]
Looks great, thanks for this

**Comment by joshzarrabi** [comment]
I'm still seeing an empty unknowns map here: https://deploy-preview-1339--health-equity-tracker.netlify.app/exploredata?mls=1.covid-3.46&demo=race_and_ethnicity&dt1=deaths

**Comment by benhammondmusic** [comment]
> I'm still seeing an empty unknowns map here: https://deploy-preview-1339--health-equity-tracker.netlify.app/exploredata?mls=1.covid-3.46&demo=race_and_ethnicity&dt1=deaths

I think this is happening because there's an error in the suppression we do somehow; related to #1267 . Like, there IS data, but not the right data, so it's showing NaN% in the legend and still rendering the map despite data. 

Should we proceed with this PR and fix that other error independently ?

**Comment by joshzarrabi** [comment]
Oh interesting, yeah why don't you make an issue for that and then we can work on that :). Lets merge this though.

**Pull request merged**
