### PR TITLE
Moving small multiples button, updating map filter text

### LINKED ISSUE #640: Modify text in the incidence/100k chart
1. Change "Filter by" to "Select group:"

2. Remove the link next to the filter 
`Show full breakdown by {selected demographic} ` 

3. Change the info alert text and use it to replace the link to "Show full breakdown"
[VIEW ALL {selected demographic} groups on one page](http://#)

### PR DESCRIPTION
**Pull request by kkatzen**
Closes #640 
Screen Shot 2021-04-22 at 11 19 48 AM

### CODE REVIEW

**Comment by achipham** [comment]
Proposed copy:
Note that legend changes between races. **Click here** to see a breakdown of all races with a common legend.

or:
Note that legend changes between races. **Click here to see all races** with a common legend.

**Comment by vanshkumar** [comment]
Is the new version clear enough? The small multiples doesn't look particularly discoverable to me now..

Screen Shot 2021-04-22 at 3 37 20 PM

**Comment by vanshkumar** [comment]
Also, are we sure that we want to have text explaining the legend here? If we change the legend to just MIN and MAX, I think it would be clear enough?

**Comment by adams314** [comment]
I'm in favor of removing the text explaining the legends and using this space to feature the small multiples map. I don't like that copy because the big win is seeing them side by side; the legend part is a technical detail.

Can we settle on:

Click to view a breakdown of all {demographic} groups

**Comment by kkatzen** [comment]
Updated with Larry's suggestion

**Review by vanshkumar — APPROVED** [review]
me gusta

**Comment by achipham** [comment]
Also should we make our link styles more consistent? Some places it's green #0b5240 and underline, some places it's green and bold. I would vote green + underline

**Comment by adams314** [comment]
I’m for what chi suggests

**Pull request merged**
