### PR TITLE
Update "What data is missing" copy

### LINKED ISSUE #639: Modify text in What Data Are Missing? on Explore Data page
### What Data are Missing?

Unfortunately there are crucial data missing in our sources. 

#### MISSING AND MISIDENTIFIED PEOPLE
Currently, there are no required or standardized race and ethnicity categories for data collection across state and local jurisdictions.  The most notable gaps exist for race and ethnic groups, physical and mental health status, and gender categories.  Many states do not record data for American Indian, Alaska Native, Native Hawaiian and Pacific Islander racial categories, lumping these people into other groups. Individuals who identify as Hispanic/Latino may not be recorded in their respective race category.  Neither disability nor mental health status is collected with the Covid case data.  Additionally, gender is recorded only as female, male, or other.  

#### MISSING CASES
For COVID related reports, this tracker uses disaggregated, individual case level data reported by states to the CDC. Unfortunately, some states have not provided this disaggregated data to the CDC, so we cannot report accurate metrics of health equity for the states of Louisiana, New Hampshire, Texas, and Wyoming. A number of other states report disaggregated data, but the number of individual cases reported to the CDC is far fewer than the aggregate numbers they report. These states' data are included, but their data should be interpreted with caution since the cases reported may not be representative of the population at large: Connecticut, Florida, Kentucky, Maryland, Michigan, Mississippi, Missouri, Nebraska, New Mexico, North Dakota, Ohio, Rhode Island, West Virginia.

####MISSING OUTCOMES
Furthermore, many of the individual COVID case records are incomplete with an unknown hospitalization and/or death status, meaning that even in states that are reporting Covid case data, we have an incomplete picture of its overall impact. Due to the nature of surveillance data, we expect this picture to become more complete over time and will use the Health Equity Tracker to record the progress.

#615

### PR DESCRIPTION
**Pull request by kkatzen**
Closes #639

### CODE REVIEW

**Comment by kkatzen** [comment]
Screen Shot 2021-04-22 at 3 38 48 PM

**Comment by kkatzen** [comment]
Screen Shot 2021-04-22 at 3 38 48 PM

**Comment by vanshkumar** [comment]
Should we bold the states that we are calling out here?

**Comment by adams314** [comment]
Good idea, I'm for bolding the states for emphasis

**Comment by kkatzen** [comment]
Bolded states

**Review by vanshkumar — APPROVED** [review]

**Pull request merged**
