### PR TITLE
Redesigns the tracker default view and madlib styling

### LINKED ISSUE #1802: Need to Improve MadLib Useability
**Describe the bug**

The Madlib feature is not clear to many people (based on UX videos)

**Expected behavior**

We need to make this UI much more clear

Some ideas:
- different color text
- different color, rounded background (more like a "button")
- default dropdown menu to "open" which forces user to either interaction or click-away; both result in an animation shrinking into the "button" and cueing that relationship
- default the setting to a "choose a condition" which forces user interaction

**Screenshots**

Possible: 
clickable

### LINKED ISSUE #1862: Update "Warm Welcome" to be more useable, and user selectable
## Is your feature request related to a problem? Please describe.

The warm welcome will no longer autoload after we merge #1782 however it could be a helpful feature for some. 

## Describe the solution you'd like

- [ ] We need to provide a link or button "Take a guided tour" that will launch the guided warm welcome
- [ ] The content needs to be updated / expanded (adding more steps perhaps) and the targets more precisely located particularly on mobile

## Describe alternatives you've considered

We could consider removing it entirely and relying on only the video and animated gifs

### PR DESCRIPTION
**Pull request by benhammondmusic**
## Preview Link

<a href="https://deploy-preview-1782--health-equity-tracker.netlify.app/exploredata" target="_blank">
  <br />
Click to demo updates </a> 

## Description

- disables the warm welcome. as default
- closes #1862 (at least partly, more could be improved)
- adds screen grabs to some warm welcome steps
- adds "guided tour" button beneath the video on the helper default screen
- adds "go back" button on the expanded topic menu when a topic is selected, which would allow a user to get back to the helper screen with the video, sample reports, and link to guided tour
- removes "X" button from warm welcome until the last step. fixes focus styles. enables scrolling / overlay highlighting. better targeting
- simplifies the UI by hiding the carousel indicator dots and nav arrows until the user selects a topic
- makes the clickable words our green link/button color; makes the non-clickable text a little less dark grey
- use border instead of underline to indicate BUTTON instead of LINK; overall increase clickability
- subtle pulse on topic button when appropriate
- default to no topic
- add responsive "helper box" in the report view space, which contain large headline asking user to click button, or quick click into various reports, and also links to context about conditions and embedded youtube video demo
- styling on carousel arrows to match the outline button look
- adds same drop shadow from our "Explore the Data" buttons to the madlib buttons; increases clickability and make styles consistent between clickable buttons
- adjusts text in the location box to fit UX best practice (dont use placeholder for instructions or labels; tell user what is searchable rather than confusing them with what isn't searchable)

## Motivation and Context

closes #1802

## Screenshots (if appropriate):

https://user-images.githubusercontent.com/41567007/198438017-d4683481-b791-443a-9ead-68ed734d741a.mp4

NEW HELPER DEFAULT PAGE
Screen Shot 2022-10-27 at 7 29 46 PM

CHANGES TO SELECTED TOPIC TRACKER PAGE 
Screen Shot 2022-10-27 at 7 29 37 PM

## Types of changes

- New feature (non-breaking change which adds functionality or content)

### CODE REVIEW

**Comment by benhammondmusic** [comment]
SCREENSHOTS VARIOUS WIDTHS

Screen Shot 2022-10-24 at 9 04 30 PM
Screen Shot 2022-10-24 at 9 04 33 PM
Screen Shot 2022-10-24 at 9 05 08 PM
Screen Shot 2022-10-24 at 9 05 17 PM
Screen Shot 2022-10-24 at 9 06 44 PM

**Comment by benhammondmusic** [comment]
playing with dynamic line height and font size to keep at least 2 cols of conditions

Screen Shot 2022-10-24 at 9 29 15 PM
Screen Shot 2022-10-24 at 9 29 24 PM
Screen Shot 2022-10-24 at 9 29 30 PM
Screen Shot 2022-10-24 at 9 29 36 PM

**Review by joshzarrabi — APPROVED** [review]
Looks amazing, thank you ben

**Review by eriwarr — APPROVED** [review]
Excellent!!!

**Pull request merged**
