### PR TITLE
Standardizes Font Sizes; Removes Dead CSS Classes

### PR DESCRIPTION
**Pull request by benhammondmusic**
- [x] eliminates dead css class CALLS and DECLARATIONS 
- [x] eliminates stray font sizes
- [x] uses `rem` for ALL font sizing in variable declarations (best practice for a11y)
- [x] uses only sass variables for all font sizes
- [x] complete manual checking across all device widths

Also removes a lot of unused CSS

### CODE REVIEW

**Comment by joshzarrabi** [comment]
@benhammondmusic
Screen Shot 2021-12-27 at 1 17 52 PM I noticed this change made the top bar text bigger. I think we
Screen Shot 2021-12-27 at 1 17 20 PM
 should fix that as it takes up even more screen real estate.

**Comment by benhammondmusic** [comment]
> @benhammondmusic Screen Shot 2021-12-27 at 1 17 52 PM I noticed this change made the top bar text bigger. I think we Screen Shot 2021-12-27 at 1 17 20 PM should fix that as it takes up even more screen real estate.
 
Good call; I actually used a nice CSS feature `clamp()` for the madlib font size, which allows a variable font size within a minimum and maximum boundary. I'll lower the maximum

**Comment by benhammondmusic** [comment]
Updating font sizing logic for the MADLIB. Here are shots at 500px (small mobile) 1200px (small desktop) 2400 (large desktop)

**Comment by joshzarrabi** [comment]
@benhammondmusic the text is still bigger for me but the top bar takes up the same amount of space so 🤷

**Review by joshzarrabi — APPROVED** [review]
This is great, thanks you!

**Pull request merged**
