### PR TITLE
Labels inside bars; mobile responsive formatting for all labels

### LINKED ISSUE #1290: Suggestion: move bar labels inside bars (when possible)
@EbonyRespress suggested a technique of moving the bar labels inside of or overlayed on the largest bars in a visible color and font to help with our issue of wanting more horizontal space to properly show disparities. This should be investigated independently of issues regarding using `k` units / adding explicit `/100k` units to the labels, as horizontal space is at a premium for these charts

### PR DESCRIPTION
**Pull request by benhammondmusic**
closes #1290 

Screen Shot 2021-11-05 at 10 30 05 AM

### CODE REVIEW

**Comment by benhammondmusic** [comment]
got it working (with hard coded cutoff)
black white labels

**Comment by benhammondmusic** [comment]
Now working using JS to calculate the breakpoint (set at 1/3 of the max value from the dataset). There is a likely a way to do it via Vega using `aggregate` but I just did it with JS instead

Screen Shot 2021-11-05 at 10 13 11 PM
Screen Shot 2021-11-05 at 10 13 32 PM

**Comment by benhammondmusic** [comment]
Added same logic to the disparity bar chart... might be worth considering. These labels are longer so compress it horizontally even more, particularly on mobile. This helps with that issue quite a bit.
Screen Shot 2021-11-05 at 10 36 33 PM

**Comment by benhammondmusic** [comment]
A few small tweaks to allow labels to display on smallest mobile screens incl multiline titles and small alignment adjustments (on mobile only)
Screen Shot 2021-11-08 at 2 08 51 PM

**Comment by benhammondmusic** [comment]
- [ ] disable “nice” on mobile to maximize horizontal space

**Review by joshzarrabi — APPROVED** [review]
I think this looks great, thanks for working on this.

**Pull request merged**
