### PR TITLE
Improve handling of`0`s on map and highest/lowest

### PR DESCRIPTION
**Pull request by benhammondmusic**
## Preview Link

<a href="https://deploy-preview-1935--health-equity-tracker.netlify.app/exploredata?mls=1.women_in_legislative_office-3.00#rate-map)" target="_blank">
  <br />
Click to demo updates </a> 

## To Do

- [x] fix behavior on expanded highest/lowest (non lowest should appear grey not yellow)

## Description

We know that there is no missing geographic data for the CAWP conditions, so we do not need to show the grey "insufficient data" box. We do however want to separate the `0%`s from the low value %s and that doesn't happen automatically using the scales we have in place. This PR isolates the zeros, and then uses a second scale to display them as a step "lighter" on the yellow/green gradient.  Eventually this could be used to isolate all mins and maxes and ultimately make our maps more colorful while still highlighting the outliers visually

This also refactors the highest/lowest functions, allowing tied mins or maxes to overrides the normal `listSize` number of values. In cases like "Middle Eastern", there is only a single state with a woman of that race, so the rest are "tied" for lowest representation. Previously it would just return first 5 states alphabetically which was misleading and confusing. 

## Motivation and Context

in prep for #1894 

## How has this been tested?

visually
unit tests added for refactored `getExtremeValues()`

## Screenshots (if appropriate):

BEFORE and AFTER
Screen Shot 2022-12-09 at 11 24 04 AM
Screen Shot 2022-12-09 at 11 25 06 AM

HIGHEST/LOWEST presenting all tied extreme values, ensuring no overlap
Screen Shot 2022-12-10 at 10 07 38 AM
Screen Shot 2022-12-10 at 10 08 37 AM

## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality or updates content)

### CODE REVIEW

**Comment by joshzarrabi** [comment]
@benhammondmusic Clicking on a state with zero causes it to crash with this error message: 

```
react-dom.production.min.js:209 TypeError: Cannot read properties of undefined (reading 'women_us_congress_pct')
    at l (datasetutils.ts:193:34)
    at Object.children (MapCard.tsx:220:53)
    at Object.children (CardWrapper.tsx:109:20)
    at Object.children (WithLoadingOrErrorUI.tsx:162:32)
    at g (WithLoadingOrErrorUI.tsx:41:16)
    at $a (react-dom.production.min.js:153:146)
    at Lo (react-dom.production.min.js:175:309)
    at _s (react-dom.production.min.js:263:406)
    at yu (react-dom.production.min.js:246:265)
    at mu (react-dom.production.min.js:246:194)
```

**Comment by benhammondmusic** [comment]
> @benhammondmusic Clicking on a state with zero causes it to crash with this error message:
> 
> ```
> react-dom.production.min.js:209 TypeError: Cannot read properties of undefined (reading 'women_us_congress_pct')
>     at l (datasetutils.ts:193:34)
>     at Object.children (MapCard.tsx:220:53)
>     at Object.children (CardWrapper.tsx:109:20)
>     at Object.children (WithLoadingOrErrorUI.tsx:162:32)
>     at g (WithLoadingOrErrorUI.tsx:41:16)
>     at $a (react-dom.production.min.js:153:146)
>     at Lo (react-dom.production.min.js:175:309)
>     at _s (react-dom.production.min.js:263:406)
>     at yu (react-dom.production.min.js:246:265)
>     at mu (react-dom.production.min.js:246:194)
> ```

good catch; i wasn't dealing with cases where the array was smaller than the `listSize`. should be fixed now. thanks!

**Review by joshzarrabi — APPROVED** [review]
Thank you Ben!

**Review by eriwarr — APPROVED** [review]
👍🏿

**Pull request merged**
