### PR TITLE
Map card: no unknown filter, default to All filter

### LINKED ISSUE #493: Data Dashboard: Default dropdowns to All
Currently, the dropdowns default to the first option in ABC order.
We want the options to default to "All".

This might be fixed by addressing #376, when "All" is moved to the top.

### LINKED ISSUE #519: Remove unknown filter from per100k mapcard
Can't calculate per100k metric for an unknown category since we don't have population info for "Unknown"

Screen Shot 2021-04-01 at 4 38 44 PM

### PR DESCRIPTION
**Pull request by kkatzen**
Closes #519
Closes #493

### CODE REVIEW

**Review by vanshkumar — COMMENTED** [review]
Looks good, but the deploy preview says "something went wrong" for me on the explore data page, do you know what's going on there?

**Comment by efregoso** [comment]
> Looks good, but the deploy preview says "something went wrong" for me on the explore data page, do you know what's going on there?

Was able to repl this

**Comment by kkatzen** [comment]
I think the deploy preview issue is the same as the dev site being down. Could you revisit this PR after y'all fix that? Thanks

**Review by vanshkumar — APPROVED** [review]
deploy preview looks good now

**Pull request merged**
