### PR TITLE
Moving overall from table to map card

### PR DESCRIPTION
**Pull request by kkatzen**
Closes the eng parts of #993

Additionally, the map card was still supporting querying for multiple breakdowns at once (age, sex, race) based on an older version that we moved away from a long time ago. I don't think we'll bring that back so I went ahead and removed that logic.

### CODE REVIEW

**Comment by joshzarrabi** [comment]
This all looks good to me, thanks @kkatzen !

**Comment by joshzarrabi** [comment]
@kkatzen do you think this would make sense to push to a branch on the main repo so I can change it later if I need to ?

**Comment by kkatzen** [comment]
> @kkatzen do you think this would make sense to push to a branch on the main repo so I can change it later if I need to ?

I think since this PR actually changes quite a bit of logic in the Map Card I'd be worried about annoying merge conflicts later if it sits in another branch for awhile- if you need to get rid of this in a hurry in the main repo I would just comment it out

**Comment by kkatzen** [comment]
> > @kkatzen do you think this would make sense to push to a branch on the main repo so I can change it later if I need to ?
> 
> I think since this PR actually changes quite a bit of logic in the Map Card I'd be worried about annoying merge conflicts later if it sits in another branch for awhile- if you need to get rid of this in a hurry in the main repo I would just comment it out

I went ahead and just disabled the text and added a todo for #993 to reenable when the copy is reviewed

**Comment by joshzarrabi** [comment]
@kkatzen Awesome, I guess the only problem is that we lose the all measure all together right now. How hard would it be to leave that in the table for now?

**Comment by kkatzen** [comment]
> @kkatzen Awesome, I guess the only problem is that we lose the all measure all together right now. How hard would it be to leave that in the table for now?

oh good catch- reverted that change and added a TODO with the new code in the comment also linked with 993 :)

**Comment by joshzarrabi** [comment]
Thank you!

**Review by joshzarrabi — APPROVED** [review]
Thank you so much!

**Pull request merged**
