### PR TITLE
Adds chart title to 100k Map

### LINKED ISSUE #1390: 100k Map should better reflect selected demographic group
### PROBLEM: 
Currently the 100k map only displays the selected demographic group in the dropdown menu (and the info box if available). The dropdown box is somewhat easy to miss, and more importantly the demographic group is not reflected in the Card Title or the Vega Legend (in RED), potentially leading to a misrepresentation of the data. 

### SOLUTION:
Using the logic from the info box (in BLUE) we can add the optional selected demographic group (eg "Black or African American", "15-24") to at least the legend, and potentially also the card title. We also need to add to the A11y descriptions being created in #1389
Screen Shot 2022-01-10 at 10 23 44 AM

### PR DESCRIPTION
**Pull request by eriwarr**
## Preview Link

<a href="https://deploy-preview-1798--health-equity-tracker.netlify.app/exploredata?onboard=false" target="_blank">
  <br />
Click to demo updates </a> 

## Description

- This PR adds a dynamic title and subtitle to the chart. 
- The title is derived from the full variable display name in the variable config object and the subtitles are derived from the demographic group to which they belong. 

## Motivation and Context

fixes #1390

## How has this been tested?

Tested locally 

## Screenshots (if appropriate):
Screen Shot 2022-09-16 at 3 06 38 PM

## Types of changes

- New feature (non-breaking change which adds functionality or content)

### CODE REVIEW

**Comment by benhammondmusic** [comment]
@eriwarr hovering on the selected demographic group in the subtitle toggles italics rn:

https://user-images.githubusercontent.com/41567007/191076220-44765ee3-a855-4838-bbaf-645e1951ceb3.mov

**Comment by benhammondmusic** [comment]
I think we need to collectively decide what we should change the "card" level titles to

**Comment by eriwarr** [comment]
> I think we need to collectively decide what we should change the "card" level titles to

Linking for reference:
https://docs.google.com/document/d/1a8QloU5UHO78VZYY0I2N3SpQTwryO2yrSTjbOZvEvfs/edit

**Comment by eriwarr** [comment]
Closing pull request as this was handled in the 2n PR.

**Pull request closed without merging**
