### PR TITLE
Improves Data Download Cards

### LINKED ISSUE #1250: Title for data download modal should wrap
image

### PR DESCRIPTION
**Pull request by benhammondmusic**
- Fixes #1250 (wrapping title on mobile instead of going off screen)
- bring some styling in line with mui grid vs CSS; keep consistent feel while making more responsive
- Adds missing info to CDC national datasets
- Adds datasource to the title of modal; helpful for UX allowing user to confirm they are downloading the correct datasource rather than the generic "this source"

data download fixes

### CODE REVIEW

**Comment by benhammondmusic** [comment]
- Standardize meta titles now that title is on modal
-

**Comment by benhammondmusic** [comment]
image

**Comment by benhammondmusic** [comment]
image

**Comment by benhammondmusic** [comment]
Fixes #1249

**Review by joshzarrabi — APPROVED** [review]
Looks great

**Pull request merged**
